-- AutoResto migration tracking (run once before other files in this folder)
BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version VARCHAR(120) NOT NULL UNIQUE,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
