-- SaaS plans, features, subscriptions, financial ledger foundation
BEGIN;

CREATE TABLE IF NOT EXISTS plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  description TEXT NULL,
  billing_interval VARCHAR(20) NOT NULL DEFAULT 'monthly',
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_plans_interval CHECK (billing_interval IN ('monthly', 'yearly', 'one_time')),
  CONSTRAINT chk_plans_price CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS features (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  feature_key VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  description TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plan_features (
  plan_id INT NOT NULL,
  feature_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (plan_id, feature_id),
  CONSTRAINT fk_plan_features_plan FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_plan_features_feature FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  plan_id INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  next_billing_date TIMESTAMP NULL,
  provider VARCHAR(30) NULL,
  provider_order_id VARCHAR(160) NULL UNIQUE,
  provider_payment_id VARCHAR(160) NULL UNIQUE,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_subscriptions_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE RESTRICT,
  CONSTRAINT chk_subscriptions_status CHECK (status IN ('pending', 'trial', 'active', 'past_due', 'suspended', 'expired', 'cancelled', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_restaurant_status ON subscriptions (restaurant_id, status, ends_at);

CREATE TABLE IF NOT EXISTS restaurant_features (
  restaurant_id INT NOT NULL,
  feature_id INT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  source VARCHAR(30) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (restaurant_id, feature_id),
  CONSTRAINT fk_restaurant_features_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_restaurant_features_feature FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS promotions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  description TEXT NULL,
  banner_url VARCHAR(500) NULL,
  cta_label VARCHAR(80) NULL,
  cta_url VARCHAR(500) NULL,
  price DECIMAL(12,2) NULL,
  discount_percent DECIMAL(5,2) NULL,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  priority INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  target_restaurant_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_promotions_restaurant FOREIGN KEY (target_restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chargeable_order_ledger (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INT NOT NULL UNIQUE,
  restaurant_id INT NOT NULL,
  charge_amount DECIMAL(12,2) NOT NULL DEFAULT 5,
  order_amount DECIMAL(12,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'chargeable',
  reason VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_chargeable_order_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_chargeable_order_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT chk_chargeable_order_status CHECK (status IN ('chargeable', 'voided', 'disputed'))
);

ALTER TABLE payment_transactions
  ADD COLUMN IF NOT EXISTS restaurant_id INT,
  ADD COLUMN IF NOT EXISTS payment_purpose VARCHAR(40) NOT NULL DEFAULT 'CUSTOMER_ORDER';

UPDATE payment_transactions pt
SET restaurant_id = o.restaurant_id
FROM orders o
WHERE o.id = pt.order_id AND pt.restaurant_id IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_transactions_restaurant'
  ) THEN
    ALTER TABLE payment_transactions
      ADD CONSTRAINT fk_payment_transactions_restaurant
      FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'chk_payment_transactions_purpose'
  ) THEN
    ALTER TABLE payment_transactions
      ADD CONSTRAINT chk_payment_transactions_purpose
      CHECK (payment_purpose IN ('CUSTOMER_ORDER', 'RESTAURANT_UPGRADE', 'RESTAURANT_SUBSCRIPTION', 'OTHER'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS payment_webhook_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(30) NOT NULL,
  event_id VARCHAR(180) NULL,
  provider_order_id VARCHAR(180) NULL,
  payload JSONB NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uniq_payment_webhook_event UNIQUE (provider, event_id)
);

CREATE TABLE IF NOT EXISTS commission_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NULL,
  commission_type VARCHAR(30) NOT NULL,
  commission_value DECIMAL(12,2) NOT NULL DEFAULT 0,
  effective_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  effective_to TIMESTAMP NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_commission_rules_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT chk_commission_type CHECK (commission_type IN ('percentage', 'fixed_per_order', 'subscription')),
  CONSTRAINT chk_commission_value CHECK (commission_value >= 0),
  CONSTRAINT chk_commission_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS financial_ledger_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  order_id INT NULL,
  payment_transaction_id INT NULL,
  entry_type VARCHAR(40) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  description VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ledger_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_ledger_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT fk_ledger_payment FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions(id) ON DELETE SET NULL,
  CONSTRAINT chk_ledger_type CHECK (entry_type IN ('customer_payment', 'commission', 'subscription_payment', 'upgrade', 'refund', 'settlement', 'adjustment'))
);

INSERT INTO plans (code, name, description, billing_interval, price)
VALUES ('starter', 'Starter', 'QR ordering, menu, kitchen and billing', 'monthly', 0)
ON CONFLICT (code) DO NOTHING;

INSERT INTO features (feature_key, name)
VALUES
  ('qr_ordering', 'QR Ordering'),
  ('basic_menu', 'Basic Menu'),
  ('orders', 'Orders'),
  ('kitchen', 'Kitchen'),
  ('billing', 'Billing'),
  ('offers', 'Offers'),
  ('coupons', 'Coupons'),
  ('inventory', 'Inventory'),
  ('advanced_analytics', 'Advanced Analytics'),
  ('customer_management', 'Customer Management'),
  ('loyalty', 'Loyalty'),
  ('whatsapp_notifications', 'WhatsApp Notifications'),
  ('advanced_reports', 'Advanced Reports')
ON CONFLICT (feature_key) DO NOTHING;

INSERT INTO plan_features (plan_id, feature_id)
SELECT p.id, f.id
FROM plans p
CROSS JOIN features f
WHERE p.code = 'starter'
  AND f.feature_key IN ('qr_ordering', 'basic_menu', 'orders', 'kitchen', 'billing')
ON CONFLICT DO NOTHING;

INSERT INTO schema_migrations (version)
VALUES ('001_saas_billing_entitlements')
ON CONFLICT (version) DO NOTHING;

COMMIT;
