-- Third-party / aggregator orders tracked per restaurant
BEGIN;

CREATE TABLE IF NOT EXISTS platform_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  platform VARCHAR(60) NOT NULL,
  external_order_id VARCHAR(120) NULL,
  customer_name VARCHAR(120) NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  commission_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  net_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'received',
  items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_platform_orders_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT chk_platform_orders_status CHECK (status IN ('received', 'preparing', 'ready', 'delivered', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_platform_orders_restaurant_created
  ON platform_orders (restaurant_id, created_at DESC);

INSERT INTO schema_migrations (version)
VALUES ('002_platform_orders')
ON CONFLICT (version) DO NOTHING;

COMMIT;
