-- Reviews, coupons, inventory, customers, refunds
BEGIN;

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  name VARCHAR(120) NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(120) NULL,
  visit_count INT NOT NULL DEFAULT 0,
  total_spent DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_customers_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_customers_restaurant_phone
  ON customers (restaurant_id, phone)
  WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS coupons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  code VARCHAR(40) NOT NULL,
  description VARCHAR(255) NULL,
  discount_type VARCHAR(20) NOT NULL DEFAULT 'percent',
  discount_value DECIMAL(12,2) NOT NULL,
  min_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  max_discount_amount DECIMAL(12,2) NULL,
  usage_limit INT NULL,
  used_count INT NOT NULL DEFAULT 0,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_coupons_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT uniq_coupons_restaurant_code UNIQUE (restaurant_id, code),
  CONSTRAINT chk_coupons_discount_type CHECK (discount_type IN ('percent', 'fixed')),
  CONSTRAINT chk_coupons_discount_value CHECK (discount_value >= 0)
);

CREATE TABLE IF NOT EXISTS coupon_redemptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id INT NOT NULL,
  order_id INT NOT NULL UNIQUE,
  restaurant_id INT NOT NULL,
  discount_amount DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_coupon_redemptions_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE,
  CONSTRAINT fk_coupon_redemptions_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_coupon_redemptions_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code VARCHAR(40) NULL;

CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  order_id INT NOT NULL UNIQUE,
  rating INT NOT NULL,
  comment TEXT NULL,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  is_moderated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reviews_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS ingredients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  unit VARCHAR(30) NOT NULL DEFAULT 'unit',
  current_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
  low_stock_threshold DECIMAL(12,3) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ingredients_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT uniq_ingredients_restaurant_name UNIQUE (restaurant_id, name)
);

CREATE TABLE IF NOT EXISTS recipes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  menu_item_id INT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_recipes_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_recipes_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS recipe_items (
  recipe_id INT NOT NULL,
  ingredient_id INT NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  PRIMARY KEY (recipe_id, ingredient_id),
  CONSTRAINT fk_recipe_items_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
  CONSTRAINT fk_recipe_items_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE,
  CONSTRAINT chk_recipe_items_quantity CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  ingredient_id INT NOT NULL,
  transaction_type VARCHAR(20) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  reference_type VARCHAR(40) NULL,
  reference_id INT NULL,
  notes VARCHAR(255) NULL,
  created_by_user_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inventory_tx_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_tx_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_tx_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_inventory_tx_type CHECK (transaction_type IN ('stock_in', 'stock_out', 'adjustment', 'consumption'))
);

CREATE TABLE IF NOT EXISTS refund_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  order_id INT NOT NULL,
  payment_transaction_id INT NULL,
  amount DECIMAL(12,2) NOT NULL,
  reason VARCHAR(255) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'requested',
  provider_refund_id VARCHAR(160) NULL,
  requested_by_user_id INT NULL,
  approved_by_user_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_refund_requests_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_refund_requests_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_refund_requests_payment FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions(id) ON DELETE SET NULL,
  CONSTRAINT chk_refund_requests_status CHECK (status IN ('requested', 'approved', 'rejected', 'processing', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_reviews_restaurant_public ON reviews (restaurant_id, is_public, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_tx_restaurant_created ON inventory_transactions (restaurant_id, created_at DESC);

INSERT INTO schema_migrations (version)
VALUES ('007_business_features')
ON CONFLICT (version) DO NOTHING;

COMMIT;
