-- GST invoicing, KOT tracking, platform team RBAC
BEGIN;

ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS legal_name VARCHAR(200) NULL;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS gstin VARCHAR(20) NULL;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS business_address VARCHAR(500) NULL;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS state_name VARCHAR(80) NULL;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS state_code VARCHAR(4) NULL;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS default_gst_rate DECIMAL(5,2) NOT NULL DEFAULT 5;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS invoice_prefix VARCHAR(20) NULL;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS fssai_license VARCHAR(30) NULL;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS invoice_counter INT NOT NULL DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_amount DECIMAL(12,2) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS taxable_amount DECIMAL(12,2) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cgst_amount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sgst_amount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS igst_amount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gst_rate DECIMAL(5,2) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(40) NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS kot_print_count INT NOT NULL DEFAULT 0;

ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20) NULL;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS gst_rate DECIMAL(5,2) NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_by_user_id INT NULL;

ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_role;
ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN (
  'super_admin', 'owner', 'kitchen', 'staff',
  'finance_manager', 'restaurant_manager', 'promotions_manager',
  'user_enquiry_manager', 'database_manager', 'backend_manager', 'analytics_manager'
));

CREATE TABLE IF NOT EXISTS platform_permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_key VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS platform_role_permissions (
  role VARCHAR(40) NOT NULL,
  permission_key VARCHAR(80) NOT NULL,
  PRIMARY KEY (role, permission_key),
  CONSTRAINT fk_prp_permission FOREIGN KEY (permission_key)
    REFERENCES platform_permissions(permission_key) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS kot_prints (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INT NOT NULL,
  restaurant_id INT NOT NULL,
  printed_by_user_id INT NULL,
  print_type VARCHAR(20) NOT NULL DEFAULT 'kot',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_kot_prints_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_kot_prints_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT fk_kot_prints_user FOREIGN KEY (printed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_kot_print_type CHECK (print_type IN ('kot', 'reprint', 'bill'))
);

CREATE INDEX IF NOT EXISTS idx_kot_prints_order ON kot_prints (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_invoice_number ON orders (invoice_number) WHERE invoice_number IS NOT NULL;

INSERT INTO platform_permissions (permission_key, name, description) VALUES
  ('restaurants.read', 'View restaurants', 'Read restaurant list and details'),
  ('restaurants.write', 'Manage restaurants', 'Create, update, suspend restaurants'),
  ('payments.read', 'View payments', 'Read payment transactions'),
  ('finance.read', 'View finance', 'Read commissions, ledger, reconciliation'),
  ('finance.write', 'Manage finance', 'Adjust commissions and settlements'),
  ('promotions.read', 'View promotions', 'Read ads and campaigns'),
  ('promotions.write', 'Manage promotions', 'Create and edit promotions'),
  ('analytics.read', 'View analytics', 'Platform and restaurant analytics'),
  ('database.read', 'Database health', 'View migration status and schema health'),
  ('database.maintenance', 'Database maintenance', 'Run safe maintenance tasks'),
  ('backend.read', 'Backend health', 'API health, logs, integration status'),
  ('backend.manage', 'Backend manage', 'Manage backend configuration'),
  ('audit.read', 'Audit logs', 'Read platform audit trail'),
  ('team.read', 'View team', 'View platform team members'),
  ('team.write', 'Manage team', 'Create and manage team members')
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO platform_role_permissions (role, permission_key) VALUES
  ('finance_manager', 'restaurants.read'),
  ('finance_manager', 'payments.read'),
  ('finance_manager', 'finance.read'),
  ('finance_manager', 'finance.write'),
  ('finance_manager', 'analytics.read'),
  ('finance_manager', 'audit.read'),
  ('restaurant_manager', 'restaurants.read'),
  ('restaurant_manager', 'restaurants.write'),
  ('restaurant_manager', 'analytics.read'),
  ('promotions_manager', 'promotions.read'),
  ('promotions_manager', 'promotions.write'),
  ('promotions_manager', 'analytics.read'),
  ('user_enquiry_manager', 'restaurants.read'),
  ('user_enquiry_manager', 'analytics.read'),
  ('database_manager', 'database.read'),
  ('database_manager', 'database.maintenance'),
  ('database_manager', 'backend.read'),
  ('backend_manager', 'backend.read'),
  ('backend_manager', 'backend.manage'),
  ('backend_manager', 'audit.read'),
  ('analytics_manager', 'analytics.read'),
  ('analytics_manager', 'restaurants.read'),
  ('analytics_manager', 'payments.read'),
  ('analytics_manager', 'finance.read')
ON CONFLICT DO NOTHING;

INSERT INTO schema_migrations (version)
VALUES ('009_gst_invoice_team_kot')
ON CONFLICT (version) DO NOTHING;

COMMIT;
