-- Menu categories for restaurant-scoped food type navigation
BEGIN;

CREATE TABLE IF NOT EXISTS menu_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INT NOT NULL,
  name VARCHAR(80) NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_menu_categories_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
  CONSTRAINT uniq_menu_categories_restaurant_name UNIQUE (restaurant_id, name)
);

CREATE INDEX IF NOT EXISTS idx_menu_categories_restaurant_order
  ON menu_categories (restaurant_id, display_order ASC, name ASC);

INSERT INTO schema_migrations (version)
VALUES ('010_menu_categories')
ON CONFLICT (version) DO NOTHING;

COMMIT;
