-- 012: Master Admin RBAC, settlements, bank vault, login activity
-- Run after 011_owner_restaurant_id_backfill.sql

BEGIN;

CREATE TABLE IF NOT EXISTS departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE,
  description TEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS platform_roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_key VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  description TEXT NULL,
  department_id INTEGER NULL REFERENCES departments(id) ON DELETE SET NULL,
  is_system BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE platform_permissions
  ADD COLUMN IF NOT EXISTS category VARCHAR(40) NULL DEFAULT 'general';

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS phone VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS username VARCHAR(80) NULL UNIQUE,
  ADD COLUMN IF NOT EXISTS department_id INTEGER NULL REFERENCES departments(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS scope_type VARCHAR(20) NOT NULL DEFAULT 'global'
    CHECK (scope_type IN ('global', 'restaurant', 'department', 'own_records')),
  ADD COLUMN IF NOT EXISTS scope_restaurant_id INTEGER NULL REFERENCES restaurants(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS user_permission_overrides (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  permission_key VARCHAR(80) NOT NULL REFERENCES platform_permissions(permission_key) ON DELETE CASCADE,
  granted BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, permission_key)
);

CREATE TABLE IF NOT EXISTS user_restaurant_assignments (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id INTEGER NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, restaurant_id)
);

CREATE TABLE IF NOT EXISTS restaurant_bank_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  account_holder_name VARCHAR(120) NOT NULL,
  bank_name VARCHAR(120) NOT NULL,
  account_number_last4 VARCHAR(4) NOT NULL,
  account_number_encrypted TEXT NULL,
  ifsc_code VARCHAR(20) NULL,
  upi_id VARCHAR(120) NULL,
  verification_status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (verification_status IN ('pending', 'verified', 'rejected', 'disabled')),
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT NULL,
  created_by_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  updated_by_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bank_accounts_restaurant ON restaurant_bank_accounts (restaurant_id, is_primary DESC);

CREATE TABLE IF NOT EXISTS settlements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  period_start TIMESTAMP NOT NULL,
  period_end TIMESTAMP NOT NULL,
  gross_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  commission_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  refund_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  adjustment_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_payable NUMERIC(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'paid', 'failed', 'on_hold', 'cancelled')),
  settlement_reference VARCHAR(80) NULL,
  settled_at TIMESTAMP NULL,
  notes TEXT NULL,
  created_by_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  updated_by_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_settlements_restaurant ON settlements (restaurant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_settlements_status ON settlements (status, created_at DESC);

CREATE TABLE IF NOT EXISTS login_activity (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  email VARCHAR(255) NULL,
  success BOOLEAN NOT NULL DEFAULT FALSE,
  ip_address VARCHAR(64) NULL,
  user_agent TEXT NULL,
  failure_reason VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_login_activity_user ON login_activity (user_id, created_at DESC);

ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS before_value JSONB NULL,
  ADD COLUMN IF NOT EXISTS after_value JSONB NULL;

ALTER TABLE restaurants
  ADD COLUMN IF NOT EXISTS onboarding_status VARCHAR(30) NOT NULL DEFAULT 'active'
    CHECK (onboarding_status IN ('onboarding', 'active', 'payment_issue', 'suspended', 'subscription_expired')),
  ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMP NULL;

-- Relax role constraint so Master Admin can create custom platform roles
ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_role;

-- Seed departments
INSERT INTO departments (name, description) VALUES
  ('Finance', 'Payments, settlements, commissions'),
  ('Operations', 'Restaurant operations and onboarding'),
  ('Marketing', 'Promotions, ads, campaigns'),
  ('Analytics', 'Platform and restaurant analytics'),
  ('Technology', 'Backend, database, system health'),
  ('Support', 'Customer and restaurant enquiries')
ON CONFLICT (name) DO NOTHING;

-- Seed platform roles from existing hardcoded roles
INSERT INTO platform_roles (role_key, name, description, department_id, is_system, status)
SELECT v.role_key, v.name, v.description, d.id, TRUE, 'active'
FROM (VALUES
  ('finance_manager', 'Finance Manager', 'Payments, settlements, commissions'),
  ('restaurant_manager', 'Restaurant Manager', 'Restaurant operations'),
  ('promotions_manager', 'Promotions Manager', 'Ads and campaigns'),
  ('user_enquiry_manager', 'User / Enquiry Manager', 'Support and enquiries'),
  ('database_manager', 'Database Manager', 'Database health and maintenance'),
  ('backend_manager', 'Backend Manager', 'API and service health'),
  ('analytics_manager', 'Analytics Manager', 'Platform analytics'),
  ('payment_manager', 'Payment Manager', 'Payment operations and reconciliation')
) AS v(role_key, name, description)
LEFT JOIN departments d ON d.name = CASE v.role_key
  WHEN 'finance_manager' THEN 'Finance'
  WHEN 'payment_manager' THEN 'Finance'
  WHEN 'restaurant_manager' THEN 'Operations'
  WHEN 'promotions_manager' THEN 'Marketing'
  WHEN 'user_enquiry_manager' THEN 'Support'
  WHEN 'database_manager' THEN 'Technology'
  WHEN 'backend_manager' THEN 'Technology'
  WHEN 'analytics_manager' THEN 'Analytics'
  ELSE 'Operations'
END
ON CONFLICT (role_key) DO NOTHING;

-- Expand permissions
INSERT INTO platform_permissions (permission_key, name, description, category) VALUES
  ('restaurants.create', 'Create restaurants', 'Onboard new restaurants', 'restaurants'),
  ('restaurants.suspend', 'Suspend restaurants', 'Suspend or restore restaurants', 'restaurants'),
  ('orders.view', 'View orders', 'Read platform orders', 'orders'),
  ('orders.export', 'Export orders', 'Export order data', 'orders'),
  ('payments.refund', 'Manage refunds', 'Approve or reject refunds', 'payments'),
  ('payments.reconcile', 'Reconcile payments', 'Payment reconciliation tools', 'payments'),
  ('settlements.view', 'View settlements', 'Read settlement records', 'settlements'),
  ('settlements.manage', 'Manage settlements', 'Create and update settlements', 'settlements'),
  ('subscriptions.view', 'View subscriptions', 'Read subscription data', 'subscriptions'),
  ('subscriptions.manage', 'Manage subscriptions', 'Assign and change plans', 'subscriptions'),
  ('features.view', 'View features', 'Read feature registry', 'features'),
  ('features.manage', 'Manage features', 'Override restaurant features', 'features'),
  ('bank_details.view', 'View bank details', 'Read masked bank details', 'finance'),
  ('bank_details.manage', 'Manage bank details', 'Add or update bank details', 'finance'),
  ('roles.view', 'View roles', 'Read role definitions', 'team'),
  ('roles.manage', 'Manage roles', 'Create and edit roles', 'team'),
  ('system.health', 'System health', 'View system health dashboard', 'system'),
  ('system.settings', 'System settings', 'Manage platform settings', 'system'),
  ('search.global', 'Global search', 'Permission-aware global search', 'system')
ON CONFLICT (permission_key) DO NOTHING;

-- Payment Manager permissions
INSERT INTO platform_role_permissions (role, permission_key) VALUES
  ('payment_manager', 'payments.read'),
  ('payment_manager', 'payments.reconcile'),
  ('payment_manager', 'finance.read'),
  ('payment_manager', 'settlements.view'),
  ('payment_manager', 'restaurants.read'),
  ('payment_manager', 'orders.view'),
  ('payment_manager', 'audit.read'),
  ('finance_manager', 'settlements.view'),
  ('finance_manager', 'settlements.manage'),
  ('finance_manager', 'payments.reconcile'),
  ('finance_manager', 'payments.refund'),
  ('finance_manager', 'bank_details.view'),
  ('finance_manager', 'bank_details.manage'),
  ('finance_manager', 'subscriptions.view'),
  ('restaurant_manager', 'restaurants.create'),
  ('restaurant_manager', 'restaurants.suspend'),
  ('restaurant_manager', 'orders.view'),
  ('analytics_manager', 'orders.view'),
  ('analytics_manager', 'settlements.view'),
  ('promotions_manager', 'features.view'),
  ('database_manager', 'system.health'),
  ('backend_manager', 'system.health'),
  ('backend_manager', 'system.settings')
ON CONFLICT DO NOTHING;

-- Grant team management to finance_manager (Master Admin still has all via bypass)
INSERT INTO platform_role_permissions (role, permission_key) VALUES
  ('finance_manager', 'team.read')
ON CONFLICT DO NOTHING;

INSERT INTO schema_migrations (version)
VALUES ('012_master_admin_rbac')
ON CONFLICT (version) DO NOTHING;

COMMIT;
