-- 013: Restaurant hub — dashboard layout, upgrade activations, features manager role

BEGIN;

ALTER TABLE restaurants
  ADD COLUMN IF NOT EXISTS dashboard_layout JSONB NULL;

CREATE TABLE IF NOT EXISTS restaurant_upgrade_activations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  payment_transaction_id INTEGER NULL REFERENCES payment_transactions(id) ON DELETE SET NULL,
  subscription_id INTEGER NULL REFERENCES subscriptions(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  provider_order_id VARCHAR(120) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'activated', 'rejected')),
  notes TEXT NULL,
  activated_by_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  activated_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_upgrade_activations_restaurant ON restaurant_upgrade_activations (restaurant_id, status);
CREATE INDEX IF NOT EXISTS idx_upgrade_activations_pending ON restaurant_upgrade_activations (status, created_at DESC)
  WHERE status = 'pending';

INSERT INTO platform_roles (role_key, name, description, department_id, is_system, status)
SELECT 'features_manager', 'Features Manager', 'Enable features after verified upgrade payments',
       d.id, TRUE, 'active'
FROM departments d WHERE d.name = 'Operations'
ON CONFLICT (role_key) DO NOTHING;

INSERT INTO platform_permissions (permission_key, name, description, category) VALUES
  ('upgrades.view', 'View upgrade payments', 'See restaurant upgrade and subscription payments', 'subscriptions'),
  ('upgrades.activate', 'Activate upgrades', 'Enable features after verified payment', 'subscriptions')
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO platform_role_permissions (role, permission_key) VALUES
  ('features_manager', 'features.view'),
  ('features_manager', 'features.manage'),
  ('features_manager', 'subscriptions.view'),
  ('features_manager', 'restaurants.read'),
  ('features_manager', 'upgrades.view'),
  ('features_manager', 'upgrades.activate'),
  ('features_manager', 'audit.read'),
  ('payment_manager', 'features.view'),
  ('payment_manager', 'upgrades.view'),
  ('finance_manager', 'upgrades.view'),
  ('finance_manager', 'upgrades.activate'),
  ('super_admin', 'upgrades.view')
ON CONFLICT DO NOTHING;

INSERT INTO schema_migrations (version)
VALUES ('013_restaurant_hub_features')
ON CONFLICT (version) DO NOTHING;

COMMIT;
