-- 014: CSV export permissions, support tickets

BEGIN;

CREATE TABLE IF NOT EXISTS support_tickets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id INTEGER NULL REFERENCES restaurants(id) ON DELETE SET NULL,
  created_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assigned_to_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  subject VARCHAR(200) NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'general'
    CHECK (category IN ('billing', 'technical', 'features', 'payout', 'general', 'other')),
  priority VARCHAR(20) NOT NULL DEFAULT 'normal'
    CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  status VARCHAR(20) NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'waiting_customer', 'resolved', 'closed')),
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_tickets_restaurant ON support_tickets (restaurant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS support_ticket_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id INTEGER NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  author_user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
  author_role VARCHAR(40) NULL,
  message TEXT NOT NULL,
  is_internal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_support_ticket_messages_ticket ON support_ticket_messages (ticket_id, created_at ASC);

INSERT INTO platform_permissions (permission_key, name, description, category) VALUES
  ('data.export', 'Export data', 'Download CSV exports for orders, settlements, restaurants', 'system'),
  ('support.view', 'View support tickets', 'Read support ticket queue', 'support'),
  ('support.manage', 'Manage support tickets', 'Assign and update ticket status', 'support'),
  ('support.respond', 'Respond to tickets', 'Reply to support tickets', 'support')
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO platform_role_permissions (role, permission_key) VALUES
  ('user_enquiry_manager', 'support.view'),
  ('user_enquiry_manager', 'support.manage'),
  ('user_enquiry_manager', 'support.respond'),
  ('user_enquiry_manager', 'orders.view'),
  ('finance_manager', 'data.export'),
  ('finance_manager', 'orders.export'),
  ('payment_manager', 'data.export'),
  ('payment_manager', 'orders.export'),
  ('analytics_manager', 'data.export'),
  ('analytics_manager', 'orders.export'),
  ('restaurant_manager', 'support.view'),
  ('features_manager', 'support.view'),
  ('super_admin', 'support.view'),
  ('super_admin', 'support.manage'),
  ('super_admin', 'support.respond'),
  ('super_admin', 'data.export')
ON CONFLICT DO NOTHING;

INSERT INTO schema_migrations (version)
VALUES ('014_exports_support_tickets')
ON CONFLICT (version) DO NOTHING;

COMMIT;
