const express = require('express');
const { z } = require('zod');

const pool = require('../config/db');
const asyncHandler = require('../utils/asyncHandler');
const { requireAuth } = require('../middleware/auth');
const { ensureRestaurantAccess } = require('../utils/access');

const router = express.Router();

const invoiceItemSchema = z.object({
  menuItemId: z.number().int().positive(),
  name: z.string().min(1),
  price: z.number().nonnegative(),
  quantity: z.number().int().positive(),
  lineTotal: z.number().nonnegative(),
});

const invoiceSyncSchema = z.object({
  orderId: z.number().int().positive(),
  tableId: z.number().int().positive(),
  restaurantId: z.number().int().positive(),
  tableNumber: z.union([z.string().min(1), z.number()]),
  customerName: z.string().optional().default(''),
  paymentStatus: z.enum(['pending', 'paid', 'failed', 'cod']).default('paid'),
  timestamp: z.string().min(1),
  totalAmount: z.number().nonnegative(),
  items: z.array(invoiceItemSchema).min(1),
});

let ensureInvoiceSyncTablePromise = null;

function ensureInvoiceSyncTable() {
  if (!ensureInvoiceSyncTablePromise) {
    ensureInvoiceSyncTablePromise = pool.query(`
      CREATE TABLE IF NOT EXISTS invoice_syncs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        restaurant_id INT NOT NULL,
        table_id INT NOT NULL,
        order_id INT NOT NULL UNIQUE,
        table_number VARCHAR(30) NOT NULL,
        customer_name VARCHAR(80) NULL,
        payment_status VARCHAR(20) NOT NULL,
        total_amount DECIMAL(10,2) NOT NULL,
        items_json JSONB NOT NULL,
        invoice_payload JSONB NOT NULL,
        synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_invoice_sync_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
        CONSTRAINT fk_invoice_sync_table FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE CASCADE,
        CONSTRAINT fk_invoice_sync_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
        CONSTRAINT chk_invoice_sync_payment_status CHECK (payment_status IN ('pending', 'paid', 'failed', 'cod'))
      )
    `);
  }

  return ensureInvoiceSyncTablePromise;
}

router.post('/sync', asyncHandler(async (req, res) => {
  await ensureInvoiceSyncTable();

  const data = invoiceSyncSchema.parse({
    ...req.body,
    orderId: Number(req.body.orderId),
    tableId: Number(req.body.tableId),
    restaurantId: Number(req.body.restaurantId),
    totalAmount: Number(req.body.totalAmount),
  });

  const tableNumber = String(data.tableNumber).trim();

  const { rows: orderRows } = await pool.query(
    'SELECT id, restaurant_id, table_id FROM orders WHERE id = $1 LIMIT 1',
    [data.orderId]
  );

  if (!orderRows.length) {
    return res.status(404).json({ message: 'Order not found' });
  }

  if (Number(orderRows[0].restaurant_id) !== data.restaurantId || Number(orderRows[0].table_id) !== data.tableId) {
    return res.status(409).json({ message: 'Invoice payload does not match order context' });
  }

  const payload = {
    ...data,
    tableNumber,
  };

  const result = await pool.query(
    `INSERT INTO invoice_syncs (
      restaurant_id, table_id, order_id, table_number, customer_name,
      payment_status, total_amount, items_json, invoice_payload, synced_at, updated_at
     ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9::jsonb, TO_TIMESTAMP($10), CURRENT_TIMESTAMP)
     ON CONFLICT (order_id)
     DO UPDATE SET
       table_number = EXCLUDED.table_number,
       customer_name = EXCLUDED.customer_name,
       payment_status = EXCLUDED.payment_status,
       total_amount = EXCLUDED.total_amount,
       items_json = EXCLUDED.items_json,
       invoice_payload = EXCLUDED.invoice_payload,
       synced_at = CURRENT_TIMESTAMP,
       updated_at = CURRENT_TIMESTAMP
     RETURNING id, synced_at`,
    [
      data.restaurantId,
      data.tableId,
      data.orderId,
      tableNumber,
      data.customerName,
      data.paymentStatus,
      data.totalAmount,
      JSON.stringify(data.items),
      JSON.stringify(payload),
      Math.floor(new Date(data.timestamp).getTime() / 1000) || Math.floor(Date.now() / 1000),
    ]
  );

  return res.status(201).json({
    message: 'Invoice synced',
    invoiceId: result.rows[0].id,
    syncedAt: result.rows[0].synced_at,
  });
}));

router.get('/restaurant/:restaurantId', requireAuth(['owner', 'super_admin', 'staff', 'kitchen']), asyncHandler(async (req, res) => {
  await ensureInvoiceSyncTable();

  const { restaurantId } = req.params;
  await ensureRestaurantAccess(req.user, restaurantId);

  const { rows } = await pool.query(
    `SELECT id, restaurant_id, table_id, order_id, table_number, customer_name, payment_status,
            total_amount, items_json, invoice_payload, synced_at, updated_at
     FROM invoice_syncs
     WHERE restaurant_id = $1
     ORDER BY synced_at DESC, id DESC
     LIMIT 100`,
    [restaurantId]
  );

  return res.json({ invoices: rows });
}));

module.exports = router;