const express = require('express');
const { z } = require('zod');
const pool = require('../config/db');
const asyncHandler = require('../utils/asyncHandler');
const { requireAuth } = require('../middleware/auth');

const router = express.Router();

const platformOrderSchema = z.object({
  restaurantId: z.number().int().positive(),
  platform: z.string().min(1),
  externalOrderId: z.string().optional().nullable(),
  customerName: z.string().optional().nullable(),
  totalAmount: z.number().nonnegative(),
  commissionAmount: z.number().nonnegative().default(0),
  status: z.enum(['received', 'preparing', 'ready', 'delivered']).default('received'),
  items: z.array(z.object({
    name: z.string().min(1),
    quantity: z.number().int().positive().default(1),
    price: z.number().nonnegative().default(0),
  })).optional(),
});

async function ensurePlatformOrdersTable() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS platform_orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      restaurant_id INT NOT NULL,
      platform VARCHAR(60) NOT NULL,
      external_order_id VARCHAR(120) NULL,
      customer_name VARCHAR(120) NULL,
      total_amount DECIMAL(10,2) NOT NULL,
      commission_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
      net_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
      status VARCHAR(20) NOT NULL DEFAULT 'received',
      items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_platform_orders_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
    );
  `);
}

router.use(requireAuth(['super_admin']));

router.get('/', asyncHandler(async (req, res) => {
  await ensurePlatformOrdersTable();
  const { rows } = await pool.query(`
    SELECT po.*, r.name AS restaurant_name
    FROM platform_orders po
    LEFT JOIN restaurants r ON r.id = po.restaurant_id
    ORDER BY po.created_at DESC
    LIMIT 200
  `);
  return res.json({ orders: rows });
}));

router.get('/summary', asyncHandler(async (req, res) => {
  await ensurePlatformOrdersTable();
  const { rows } = await pool.query(`
    SELECT platform, COUNT(*)::int AS order_count, COALESCE(SUM(total_amount), 0)::numeric AS gross_revenue
    FROM platform_orders
    GROUP BY platform
    ORDER BY order_count DESC
  `);
  return res.json({ summary: rows });
}));

router.post('/', asyncHandler(async (req, res) => {
  await ensurePlatformOrdersTable();

  const data = platformOrderSchema.parse({
    ...req.body,
    restaurantId: Number(req.body.restaurantId),
    totalAmount: Number(req.body.totalAmount),
    commissionAmount: Number(req.body.commissionAmount || 0),
  });

  const netAmount = Number(data.totalAmount) - Number(data.commissionAmount);
  const itemsJson = JSON.stringify(data.items || []);

  const { rows } = await pool.query(
    `INSERT INTO platform_orders (
       restaurant_id, platform, external_order_id, customer_name,
       total_amount, commission_amount, net_amount, status, items_json
     ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
     RETURNING *`,
    [
      data.restaurantId,
      data.platform,
      data.externalOrderId || null,
      data.customerName || null,
      data.totalAmount,
      data.commissionAmount,
      netAmount,
      data.status,
      itemsJson,
    ]
  );

  return res.status(201).json({ order: rows[0] });
}));

router.patch('/:orderId/status', asyncHandler(async (req, res) => {
  const orderId = Number(req.params.orderId);
  const status = String(req.body.status || '').trim();
  const validStatuses = ['received', 'preparing', 'ready', 'delivered'];

  if (!validStatuses.includes(status)) {
    return res.status(400).json({ message: 'Invalid status' });
  }

  const { rows } = await pool.query(
    `UPDATE platform_orders
     SET status = $1, updated_at = CURRENT_TIMESTAMP
     WHERE id = $2
     RETURNING *`,
    [status, orderId]
  );

  if (!rows.length) {
    return res.status(404).json({ message: 'Platform order not found' });
  }

  return res.json({ order: rows[0] });
}));

module.exports = router;
