const pool = require('../config/db');

async function ensureSaasSchema() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS ads (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title VARCHAR(120) NOT NULL,
      image_url VARCHAR(255),
      video_url VARCHAR(255),
      media_type VARCHAR(40) NOT NULL DEFAULT 'image',
      display_mode VARCHAR(40) NOT NULL DEFAULT 'grid',
      display_order INT DEFAULT 0,
      target_link VARCHAR(255),
      restaurant_id INT NULL,
      is_active BOOLEAN DEFAULT TRUE,
      starts_at TIMESTAMP NULL,
      ends_at TIMESTAMP NULL,
      impressions INT DEFAULT 0,
      clicks INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_ads_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
    )
  `);

  await pool.query(`ALTER TABLE IF NOT EXISTS restaurants ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(80);`);
  await pool.query(`ALTER TABLE IF NOT EXISTS restaurants ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(40);`);
  await pool.query(`ALTER TABLE IF NOT EXISTS restaurants ADD COLUMN IF NOT EXISTS subscription_expires_at TIMESTAMP;`);
  await pool.query(`ALTER TABLE IF NOT EXISTS restaurants ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500);`);
  await pool.query(`ALTER TABLE IF NOT EXISTS restaurants ADD COLUMN IF NOT EXISTS thank_you_message VARCHAR(255);`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS platform_orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      restaurant_id INT NOT NULL,
      platform VARCHAR(60) NOT NULL,
      external_order_id VARCHAR(120) NULL,
      customer_name VARCHAR(120) NULL,
      total_amount DECIMAL(10,2) NOT NULL,
      commission_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
      net_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
      status VARCHAR(20) NOT NULL DEFAULT 'received',
      items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_platform_orders_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS invoice_syncs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      restaurant_id INT NOT NULL,
      table_id INT NOT NULL,
      order_id INT NOT NULL UNIQUE,
      table_number VARCHAR(30) NOT NULL,
      customer_name VARCHAR(80) NULL,
      payment_status VARCHAR(20) NOT NULL,
      total_amount DECIMAL(10,2) NOT NULL,
      items_json JSONB NOT NULL,
      invoice_payload JSONB NOT NULL,
      synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_invoice_sync_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
      CONSTRAINT fk_invoice_sync_table FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE CASCADE,
      CONSTRAINT fk_invoice_sync_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
      CONSTRAINT chk_invoice_sync_payment_status CHECK (payment_status IN ('pending', 'paid', 'failed', 'cod'))
    )
  `);
}

module.exports = {
  ensureSaasSchema,
};
